### PR TITLE
feat: volume table

### PR DESCRIPTION
**Pull request by wg102**
closes https://github.com/StatCan/jupyter-apis/issues/71

The is no colors in the status and the table is only in minimal width. 
but it's that, or we hardcode the width.

### CODE REVIEW

**Comment by Jose-Matsuda** [comment]
fwiw I also included the `proxy.config.js` in my own push, as well as the change to the `package.json` for the `npm start`
https://github.com/StatCan/jupyter-apis/pull/79

**Comment by Jose-Matsuda** [comment]
This is what it looks like locally btw
image

I think maybe we _should_ hardcode the notebook volumes size just to make it at least look consistent.

**Review by Jose-Matsuda — APPROVED** [review]
lgtm

**Comment by wg102** [comment]
The visual with the width hardcoded: 
image

**Comment by Jose-Matsuda** [comment]
Closed by https://github.com/StatCan/jupyter-apis/pull/92

**Pull request closed without merging**
