### PR TITLE
feat(hide info): Bring back the hide-registry version

### LINKED ISSUE #78: JWA Customization: Bring in "Implement hiding registry and tag in image dropdown"
Basically bring in https://github.com/StatCan/kubeflow/issues/51 as there are changes that we need to bring in. 

Just review the changes in https://github.com/kubeflow/kubeflow/pull/5681 and bring it in

### PR DESCRIPTION
**Pull request by Jose-Matsuda**
Closes #78

### CODE REVIEW

**Comment by Jose-Matsuda** [comment]
Also commit in the easier way to test (the proxy.config)

**Comment by sylus** [comment]
Can i get confirmation this has been tested? Thanks :)

**Comment by Jose-Matsuda** [comment]
@sylus I have tested locally (using minikf as a cluster) and this is just to get the `image` selection matching what we have in prod. 

image

This change was brought in by Jessica / Saffa upstream before but did not make it into the 1.3 cutoff. 

Before this change / on main / on dev currently
image

**Comment by rohank07** [comment]
Closing this PR, merged `bring-back-hide-registry-version` into `feat-custom-url `

**Pull request closed without merging**
